apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
  namespace: default
spec:
  replicas: 9
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - image: localhost:5000/demo-image
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          imagePullPolicy: Always
          name: demo-image
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
